server:
  port: 8002

spring:
  application:
    name: ms-domain-meetup-api
  datasource:
    username: santander
    password: admin
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
  sleuth:
    sampler:
      probability: 1.0
    web:
      skipPattern: (^cleanup.*|.+favicon.*|.+management.*)
    enabled: true
  zipkin:
    base-url: http://localhost:9411/
    enabled: false

springdoc:
  show:
    actuator: true