server:
  port: 8002

spring:
  application:
    name: ms-domain-meetup-api
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  sleuth:
    sampler:
      probability: 1.0
    web:
      skipPattern: (^cleanup.*|.+favicon.*|.+management.*)
    enabled: true
  zipkin:
    base-url: http://localhost:9411/
    enabled: false

springdoc:
  show:
    actuator: true